Replace pytz and tzlocal by zoneinfo
vit-project/vit pull request #299
Opened 2021-07-24 21:01 UTC by jspricke

Requires Python 3.9

2021-07-25 00:33 UTC, thehunmonkgroup commented
This will be welcome, but it's much too soon from a compatibility standpoint -- there are important distros not running 3.9 yet.

2022-03-15 06:42 UTC, jspricke commented
Hi, https://github.com/GothenburgBitFactory/tasklib/pull/109 was merged and I added a backports dependency for old Python version. Do you think this is ready for merging?

2022-03-15 13:48 UTC, thehunmonkgroup requested changes

2022-03-15 13:48 UTC, thehunmonkgroup commented on vit/formatter/__init__.py
> +from zoneinfo import ZoneInfo
The documentation at https://pypi.org/project/backports.zoneinfo/ is suggesting this idiom for the fallback:

```python
try:
    import zoneinfo
except ImportError:
    from backports import zoneinfo
```

Is there some reason the official documentation suggestion is not being followed?

2022-03-15 13:48 UTC, thehunmonkgroup commented on vit/formatter_base.py
> +from zoneinfo import ZoneInfo
Same as previous fallback question.

2022-03-15 14:10 UTC, jspricke commented
>The documentation at https://pypi.org/project/backports.zoneinfo/ is suggesting this idiom for the fallback:
>
>```python
>try:
>    import zoneinfo
>except ImportError:
>    from backports import zoneinfo
>```
>
>Is there some reason the official documentation suggestion is not being followed?

Fixed, thx.

2022-03-15 14:28 UTC, thehunmonkgroup commented
Can you provide any clarity what ```pytz``` and ```tzlocal``` are still being installed despite not being listed in the requirements any more?

```
[:~/git/vit] jspricke-zoneinfo+ ± cat requirements.txt 
tasklib>=2.4.0
urwid>=2.1.0
backports.zoneinfo;python_version<"3.9"
[:~/git/vit] jspricke-zoneinfo+ ± pip install -r requirements.txt
Collecting tasklib>=2.4.0
  Using cached tasklib-2.4.3-py3-none-any.whl
Requirement already satisfied: urwid>=2.1.0 in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: backports.zoneinfo in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.2.1)
Collecting pytz
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting tzlocal
  Using cached tzlocal-4.1-py3-none-any.whl (19 kB)
Requirement already satisfied: pytz-deprecation-shim in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from tzlocal->tasklib>=2.4.0->-r requirements.txt (line 1)) (0.1.0.post0)
Requirement already satisfied: tzdata in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal->tasklib>=2.4.0->-r requirements.txt (line 1)) (2021.5)
Installing collected packages: tzlocal, pytz, tasklib
Successfully installed pytz-2021.3 tasklib-2.4.3 tzlocal-4.1
```

2022-03-15 14:32 UTC, jspricke commented
>Can you provide any clarity what ```pytz``` and ```tzlocal``` are still being installed despite not being listed in the requirements any more?
[..]
>Requirement already satisfied: pytz-deprecation-shim in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from tzlocal->tasklib>=2.4.0->-r requirements.txt (line 1)) (0.1.0.post0)
>Requirement already satisfied: tzdata in /home/hunmonk/.pyenv/versions/3.7.4/lib/python3.7/site-packages (from pytz-deprecation-shim->tzlocal->tasklib>=2.4.0->-r requirements.txt (line 1)) (2021.5)

Because the pip version of tasklib still depends on them.

2022-03-15 14:47 UTC, thehunmonkgroup commented
Got it. So it seems sensible to wait until the next release of ```tasklib```, then we can properly bump the dependencies.

2022-03-15 14:51 UTC, jspricke commented
* thehunmonkgroup ***@***.***> [2022-03-15 07:47]:
>Got it. So it seems sensible to wait until the next release of ```tasklib```, then we can properly bump the dependencies.

Just to ask, does it make any difference for vit? As long as the 
dependencies are not imported in vit they should not be used, right?

2022-03-15 15:02 UTC, thehunmonkgroup commented
> Just to ask, does it make any difference for vit? As long as the
> dependencies are not imported in vit they should not be used, right?

Correct. I suppose we could commit this now and simply delay the 2.2.0 release until after we bump the ```tasklib``` deps. I think it just makes for a cleaner overall experience to coordinate that.

2022-03-15 15:03 UTC, merged